"""Complete yoga pose name mapping - 107 poses with EN/ZH/SK names."""

# English -> Chinese mapping
EN_TO_ZH = {
    # Standing
    "Mountain Pose": "山式",
    "Standing Forward Bend": "站立前屈式",
    "Standing Big Toe Hold": "站立手抓大脚趾式",
    "Extended Hand-To-Big-Toe Pose": "站立手抓大脚趾伸展式",
    "Standing Hand-To-Big-Toe Pose": "站立手抓大脚趾式",
    "Tree Pose": "树式",
    "Tree Pose Vrksasana": "树式",
    "Eagle Pose": "鹰式",
    "Warrior I": "战士一式",
    "Warrior I Pose": "战士一式",
    "Warrior II": "战士二式",
    "Warrior II Pose": "战士二式",
    "Warrior III": "战士三式",
    "Warrior III Pose": "战士三式",
    "Triangle Pose": "三角式",
    "Extended Triangle Pose": "三角伸展式",
    "Extended Side Angle Pose": "侧角伸展式",
    "Side Angle Pose": "侧角式",
    "Chair Pose": "幻椅式",
    "Garland Pose": "花环式",
    "High Lunge": "高位弓步",
    "Low Lunge": "低位弓步",
    "Half Moon Pose": "半月式",
    "Half Moon Pose Ardha": "半月式",
    "Revolved Triangle": "扭转三角式",
    "Revolved Triangle Pose": "扭转三角式",
    "Revolved Side Angle": "扭转侧角式",
    "Revolved Side Angle Pose": "扭转侧角式",
    "Pyramid Pose": "加强侧伸展式",
    "Intense Side Stretch Pose": "加强侧伸展式",
    "Reverse Warrior": "反战式",
    "Standing Half Forward Bend": "站立半前屈式",
    "Standing Split": "站立劈叉式",
    "Standing Separate Leg Head To Knee": "站立分腿头触膝式",
    "Standing Separate Leg Stretching": "站立分腿伸展式",
    "Standing Bow Pulling Pose": "站立拉弓式",
    "Standing Bow Pose": "站立弓式",
    "Standing Head To Knee": "站立头触膝式",
    "Standing Leg Raise": "站立抬腿式",
    "Standing Reach Up": "站立上举式",
    "Wide Legged Forward Bend": "站立分腿前屈式",
    "Wide-Legged Forward Bend": "站立分腿前屈式",
    "Gate Pose": "门闩式",
    "Big Toe Pose": "大脚趾式",
    "Victory Pose": "胜利式",
    "Upward Salute": "手臂上举式",
    "Upward Salute Urdhva Hastasana": "手臂上举式",
    "Balance Pose": "平衡式",
    "Wild Thing": "狂野式",

    # Seated
    "Easy Pose": "简易坐",
    "Staff Pose": "手杖式",
    "Hero Pose": "英雄式",
    "Reclining Hero Pose": "仰卧英雄式",
    "Lotus Pose": "莲花式",
    "Half Lotus Pose": "半莲花式",
    "Boat Pose": "船式",
    "Bound Angle Pose": "束角式",
    "Half Bound Angle Pose": "半束角式",
    "Head-to-Knee Forward Bend": "单腿背部伸展式",
    "Seated Forward Bend": "坐立前屈式",
    "Seated Side Bend": "坐立侧弯式",
    "Seated Straddle": "坐立分腿式",
    "Seated Straddle Forward Bend": "坐立分腿前屈式",
    "Wide-Angle Seated Forward Bend": "坐角式",
    "Sitting Head To Knee": "坐立头触膝式",
    "Half Lord of the Fishes Pose": "半鱼王式",
    "Revolved Head-To-Knee Pose": "扭转单腿背部伸展式",
    "Revolved Head-to-Knee Pose": "扭转单腿背部伸展式",
    "Fire Log Pose": "火炉式",
    "Cow Face Pose": "牛面式",
    "Heron Pose": "鹭式",
    "Tortoise Pose": "龟式",
    "Yoga Mudra": "瑜伽契印式",
    "Sage Pose": "圣哲式",
    "Sage Twist": "圣哲扭转式",
    "Spine Twisting Pose": "脊柱扭转式",
    "Marichi's Pose": "马里奇式",
    "Pose Dedicated to the Sage Marichi I": "圣哲马里奇一式",
    "Pose Dedicated to the Sage Koundinya I": "圣哲康迪亚一式",
    "Pose Dedicated to the Sage Koundinya II": "圣哲康迪亚二式",
    "Scale Pose": "天秤式",
    "Noose Pose": "套索式",
    "Monkey Pose": "神猴式",
    "Yogic Sleep": "瑜伽睡眠式",

    # Prone
    "Cobra Pose": "眼镜蛇式",
    "Locust Pose": "蝗虫式",
    "Bow Pose": "弓式",
    "Sphinx Pose": "狮身人面式",
    "Half Frog Pose": "半蛙式",
    "Crocodile Pose": "鳄鱼式",
    "Salabhasana": "蝗虫式",
    "Frog Pose": "青蛙式",
    "Embryo in Womb Pose": "胎儿式",

    # Supine
    "Bridge Pose": "桥式",
    "Wheel Pose": "轮式",
    "Upward Bow (Wheel) Pose": "轮式",
    "Upward Plank Pose": "反斜板式",
    "Fish Pose": "鱼式",
    "Reclining Bound Angle": "仰卧束角式",
    "Reclining Bound Angle Pose": "仰卧束角式",
    "Reclining Hand-To-Big-Toe": "仰卧手抓大脚趾式",
    "Reclining Hand-to-Big-Toe Pose": "仰卧手抓大脚趾式",
    "Supine Spinal Twist": "仰卧脊柱扭转式",
    "Lying Half Lord of the Fishes Pose": "仰卧半鱼王式",
    "Happy Baby Pose": "快乐婴儿式",
    "Wind Removing Pose": "排气式",
    "Corpse Pose": "摊尸式",
    "Corpse Pose Savasana": "摊尸式",
    "Legs-Up-the-Wall Pose": "倒箭式",
    "Legs Up The Wall": "倒箭式",

    # Backbends
    "Camel Pose": "骆驼式",
    "Cat Pose": "猫式",
    "Cow Pose": "牛式",
    "Cat Cow Pose": "猫牛式",
    "Upward-Facing Dog": "上犬式",
    "Upward Facing Dog": "上犬式",
    "Upward-Facing Dog Pose": "上犬式",
    "Child's Pose": "婴儿式",
    "Extended Puppy Pose": "小狗伸展式",
    "Knees, Chest and Chin Pose": "八体投地式",
    "Lion Pose": "狮子式",

    # Arm balances
    "Crane (Crow) Pose": "乌鸦式",
    "Crow Pose": "乌鸦式",
    "Side Plank": "侧板式",
    "Side Plank Pose": "侧板式",
    "Four-Limbed Staff Pose": "四柱支撑",
    "Dolphin Plank Pose": "海豚平板式",
    "Plank Pose": "平板式",
    "Eight-Angle Pose": "八角式",
    "Firefly Pose": "萤火虫式",
    "Peacock Pose": "孔雀式",
    "Side Crane (Crow) Pose": "侧乌鸦式",
    "Bhujapidasana": "臂压式",
    "Pendant Pose": "悬挂式",
    "Formidable Pose": "强力式",
    "Formidable Face/Chin Stand Pose": "下巴倒立式",

    # Inversions
    "Downward-Facing Dog": "下犬式",
    "Dolphin Pose": "海豚式",
    "Shoulder Stand": "肩倒立",
    "Supported Shoulderstand": "支撑肩倒立",
    "Headstand": "头倒立",
    "Supported Headstand": "支撑头倒立",
    "Plow Pose": "犁式",
    "Feathered Peacock Pose": "羽毛孔雀式",
    "Pincha Mayurasana": "孔雀式",
    "Handstand": "手倒立",
    "Scorpion Pose": "蝎子式",

    # Balancing
    "Side-Reclining Leg Lift": "侧卧抬腿式",
    "Toe Stand Pose": "脚趾站立式",
    "Standing Separate Leg Head To Knee Pose": "站立分腿头触膝式",
    "Lord of the Dance Pose": "舞王式",
    "Dancer Pose": "舞王式",
    "One-Legged King Pigeon Pose": "单腿鸽王式",
    "One-Legged King Pigeon Pose II": "单腿鸽王二式",
    "Pigeon Pose": "鸽子式",
    "Durvasasana": "圣者 Durvasa 式",
    "Anantasana": "侧卧抬腿式",

    # Twist
    "Revolved Prayer Twist": "祈祷扭转式",
    "Revolved Half Moon": "扭转半月式",
    "Bharadvaja's Twist": "巴拉瓦伽扭转式",

    # Restorative
    "Table Top Pose": "桌式",
    "Thread The Needle": "穿针式",
    "Thunderbolt Pose": "雷电坐",
    "Squatting": "蹲式",
    "Yogi Squat": "瑜伽蹲式",
}

# English -> Sanskrit mapping (common ones)
EN_TO_SK = {
    "Mountain Pose": "Tadasana",
    "Standing Forward Bend": "Uttanasana",
    "Tree Pose": "Vrksasana",
    "Eagle Pose": "Garudasana",
    "Warrior I": "Virabhadrasana I",
    "Warrior II": "Virabhadrasana II",
    "Warrior III": "Virabhadrasana III",
    "Triangle Pose": "Trikonasana",
    "Chair Pose": "Utkatasana",
    "Half Moon Pose": "Ardha Chandrasana",
    "Cobra Pose": "Bhujangasana",
    "Downward-Facing Dog": "Adho Mukha Svanasana",
    "Boat Pose": "Navasana",
    "Bridge Pose": "Setu Bandhasana",
    "Camel Pose": "Ustrasana",
    "Crow Pose": "Bakasana",
    "Shoulder Stand": "Sarvangasana",
    "Headstand": "Sirsasana",
    "Plow Pose": "Halasana",
    "Fish Pose": "Matsyasana",
    "Lotus Pose": "Padmasana",
    "Corpse Pose": "Savasana",
    "Easy Pose": "Sukhasana",
    "Staff Pose": "Dandasana",
    "Cobra Pose": "Bhujangasana",
    "Locust Pose": "Salabhasana",
    "Bow Pose": "Dhanurasana",
    "Wheel Pose": "Urdhva Dhanurasana",
    "Plank Pose": "Phalakasana",
    "Side Plank": "Vasisthasana",
    "Dolphin Pose": "Ardha Pincha Mayurasana",
    "Pigeon Pose": "Eka Pada Rajakapotasana",
    "Hero Pose": "Virasana",
    "Child's Pose": "Balasana",
    "Cat Pose": "Marjaryasana",
    "Cow Pose": "Bitilasana",
    "Sphinx Pose": "Salamba Bhujangasana",
    "Garland Pose": "Malasana",
    "Bound Angle Pose": "Baddha Konasana",
    "Head-to-Knee Forward Bend": "Janu Sirsasana",
    "Seated Forward Bend": "Paschimottanasana",
    "Half Lord of the Fishes Pose": "Ardha Matsyendrasana",
    "Cow Face Pose": "Gomukhasana",
    "Extended Side Angle Pose": "Utthita Parsvakonasana",
    "Revolved Triangle": "Parivrtta Trikonasana",
    "Revolved Side Angle": "Parivrtta Parsvakonasana",
    "Pyramid Pose": "Parsvottanasana",
    "Half Bound Angle Pose": "Baddha Konasana",
    "Happy Baby Pose": "Ananda Balasana",
    "Legs-Up-the-Wall Pose": "Viparita Karani",
    "Fire Log Pose": "Agnistambhasana",
    "Monkey Pose": "Hanumanasana",
    "Upward-Facing Dog": "Urdhva Mukha Svanasana",
    "Standing Forward Bend": "Uttanasana",
    "Four-Limbed Staff Pose": "Chaturanga Dandasana",
    "Eight-Angle Pose": "Astavakrasana",
    "Firefly Pose": "Tittibhasana",
    "Side Crane (Crow) Pose": "Parsva Bakasana",
    "Scorpion Pose": "Vrschikasana",
    "Feathered Peacock Pose": "Pincha Mayurasana",
    "Supported Headstand": "Salamba Sirsasana",
    "Supported Shoulderstand": "Salamba Sarvangasana",
    "Upward Plank": "Purvottanasana",
    "Reclining Hero Pose": "Supta Virasana",
    "Reclining Bound Angle": "Supta Baddha Konasana",
    "Reclining Hand-to-Big-Toe Pose": "Supta Padangusthasana",
    "Wild Thing": "Camatkarasana",
    "Lion Pose": "Simhasana",
    "Yogic Sleep": "Yoga Nidra",
    "Scale Pose": "Tolasana",
    "Noose Pose": "Pasasana",
    "Dancer Pose": "Natarajasana",
    "Lord of the Dance Pose": "Natarajasana",
    "One-Legged King Pigeon Pose": "Eka Pada Rajakapotasana",
    "Frog Pose": "Mandukasana",
    "Extended Puppy Pose": "Uttana Shishosana",
    "Low Lunge": "Anjaneyasana",
    "High Lunge": "Utthita Ashwa Sanchalanasana",
    "Table Top Pose": "Bharmanasana",
    "Thread The Needle": "Parsva Balasana",
    "Thunderbolt Pose": "Vajrasana",
    "Upward-Facing Two-Foot Staff Pose": "Dwi Pada Viparita Dandasana",
    "Pose Dedicated to the Sage Koundinya I": "Eka Pada Koundinyasana I",
    "Pose Dedicated to the Sage Koundinya II": "Eka Pada Koundinyasana II",
    "Pose Dedicated to the Sage Marichi I": "Marichyasana I",
    "Intense Side Stretch Pose": "Parsvottanasana",
    "Revolved Half Moon": "Parivrtta Ardha Chandrasana",
    "Revolved Prayer Twist": "Parivrtta Utkatasana",
    "Bharadvaja's Twist": "Bharadvajasana",
    "Extended Hand-To-Big-Toe Pose": "Utthita Hasta Padangusthasana",
    "Standing Separate Leg Stretching": "Prasarita Padottanasana",
    "Standing Bow Pulling Pose": "Dandayamana Dhanurasana",
    "Standing Head To Knee": "Dandayamana Janushirasana",
    "Standing Leg Raise": "Dandayamana Pada Hastasana",
    "Standing Reach Up": "Urdhva Hastasana",
    "Wide-Legged Forward Bend": "Prasarita Padottanasana",
    "Standing Half Forward Bend": "Ardha Uttanasana",
    "Standing Split": "Urdhva Prasarita Eka Padasana",
    "Half Frog Pose": "Ardha Bhekasana",
    "Embryo in Womb Pose": "Garbhasana",
    "Anantasana": "Anantasana",
    "Upward Bow (Wheel) Pose": "Urdhva Dhanurasana",
    "Legs Up The Wall": "Viparita Karani",
    "Upward Facing Dog": "Urdhva Mukha Svanasana",
    "Upward-Facing Dog Pose": "Urdhva Mukha Svanasana",
    "Upward Salute Urdhva Hastasana": "Urdhva Hastasana",
}

def get_names(english_name):
    """Get Chinese and Sanskrit names for an English pose name."""
    zh = EN_TO_ZH.get(english_name, english_name)
    sk = EN_TO_SK.get(english_name, "")
    return zh, sk

# Test
if __name__ == "__main__":
    import json
    with open('external_data/pose_meta.json') as f:
        external = json.load(f)
    
    print(f"Total poses: {len(external)}")
    
    # Check coverage
    zh_count = sum(1 for p in external if p['english_name'] in EN_TO_ZH)
    sk_count = sum(1 for p in external if p['english_name'] in EN_TO_SK)
    
    print(f"Chinese names: {zh_count}/{len(external)}")
    print(f"Sanskrit names: {sk_count}/{len(external)}")
    
    # Show sample
    print("\nSample mappings:")
    for pose in external[:10]:
        zh, sk = get_names(pose['english_name'])
        print(f"  {pose['english_name']:35s} -> {zh:15s} | {sk}")
