"""Render a human-review diff: current data/asanas.json vs the
calibration-produced data/asanas.suggested.json, annotated with how many
reference poses backed each asana and a trust flag.

Trust flags:
  UNCAL    no reference poses (crow, handstand, extended_hand_to_toe) -> keep current
  SINGLE   1-2 refs -> suggestion too weak, keep current
  NOISY    >=3 refs but std very high -> tol unreliable, clamp if merged
  ROBUST   >=3 refs, moderate std -> suggestible
"""
from __future__ import annotations
import json, os, glob

CUR = "data/asanas.json"
SUG = "data/asanas.suggested.json"
REF = "data/ref"
OUT = "docs/calibration_diff.md"


def refcount(aid):
    d = os.path.join(REF, aid)
    return len(glob.glob(os.path.join(d, "ref_*.json"))) if os.path.isdir(d) else 0


def trust(rc, std):
    if rc == 0:
        return "UNCAL"
    if rc < 3:
        return "SINGLE"
    if std is not None and std > 25:
        return "NOISY"
    return "ROBUST"


cur = json.load(open(CUR))
sug = json.load(open(SUG))
by_id = {a["id"]: a for a in sug["asanas"]}

out = ["# Calibration Diff — current vs video-suggested", "",
       "Generated by tools/calibration_diff.py. Review before merging into data/asanas.json.",
       "", "| asana | refs | trust | rule | cur target | sug target | cur tol | sug tol |",
       "|---|---|---|---|---|---|---|---|"]

for a in cur["asanas"]:
    aid = a["id"]
    rc = refcount(aid)
    sa = by_id.get(aid)
    if rc == 0 or not sa:
        out.append(f"| {aid} | {rc} | UNCAL | (all rules) | — | — | — | — |")
        continue
    for r in a["rules"]:
        rid = r["id"]
        sr = next((x for x in sa["rules"] if x["id"] == rid), None)
        if not sr:
            continue
        ct, st = r.get("target"), sr.get("target")
        ctl = r.get("tol", r.get("min_sep"))
        stl = sr.get("tol", sr.get("min_sep"))
        # recover std for trust from suggested tol (approx: tol = max(std*2, floor))
        std = (stl - (5.0 if r["type"] != "level" else 0.03)) / 2.0 if stl else 0
        tr = trust(rc, std)
        out.append(f"| {aid} | {rc} | {tr} | {rid} | {ct} | {st} | {ctl} | {stl} |")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print("wrote", OUT, "—", len(out) - 6, "rule rows")
